[package]
name = "audrey"
version = "0.1.0"
authors = ["John Jannotti <jj@jannotti.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.7"
